dist: xenial
addons:
  chrome: stable
language: node_js
install:
- npm ci
- npm run webdriver:update
cache:
  directories:
  - node_modules
env:
  global:
  - secure: Zc/RCWLBmxbCJWBzphtYJh/qNHACIRQJY9zNuSnkg9S0yOau3ZvHcIPtVSyGhf6UeKZtRyKAIwtn0xdLwcOUgAXZ521BS8oynq8LnV159r9fVmCIz0dYO5AToAFk9Ws5nsUwdgeGNkUpM9A8SM6pBRdUoIXMtRUQd0g0FHyuQhyFgukymkrQwYrEy5HgfHttokiFNbTCvUtewZikMx2RxdhVmRL0OPCBBo5hyZfBiTjlMHieVQEpllkZncpfGAUlk/fcbOzjX/4tfjo/itfhI5aC1I1uUWlZ4B8riBI/rnrM6QzKp7ku3bKhIaDcd9HsUl89zckWnbnm++vynZvT1+AZ9NTbV1dbX4XVCPt4fa2rDyPydxkJdw23qerjdfIuT/6tGNALl+mfE3JuuOWSSglro18m8d2IoskpxOMledEQjq91zI94Vbq9Vx2nUKwtPGHOnX9s+fJ1cCQTgw8YUANnJsghC/O07CLCF8BJyH90GHGw55E9g9RB068hoOvVak+UeMqfgR0meFf30liUjRClguO1vjanVecZXXlMNvW4l8TpWIqtgVfwwTF8Sx0dNDNbGlcbnTIK7hYdwkPvHr+yKV0jOGyGGlwATG+BYMlStx7eUVDS8MgHJ2/FX2x49loI2wxDugebwOJ+ikzC4dy/Zg5Q6hGW9zJWR0lk4NU=
  - secure: H2b+K1aR8Z5Y6DkqDuCNf2rFWGBqYA0ZgA+P0mUOytZF2VNqM6kZne6v2JOg+eLbOXcuqjyrpibM73OVn8WUwg2HFnmfZGnk1v+U58eizUUBsomCRFq3dYGK1nRuUrbbxSbQEJFbD1wUOM7m1Z7i5KenbSlvRzxVh9fHlKnhPltd0F8lRNP/HekH/cEL+o6WdwXi804YehmXsTPFrHprt0VwLmY/nrm0+ZhmXPaV4MiFNkd/I/srlioF7i8FDRmRxT1Ql9RZnwGVQBPlPlPL7OQQWMcuOaIq0HYPpwsEtVvyxy1Sl+4GvPkOdpU0Ox/W9g4x88C+uMEoUPz5xMOsSEQqglLUAwT9rblUxSP/Td4ZfjySN8axGXgeTdfFoaOxu7TOxVvLBfFkgDFECC+tPZHbjdMMn7B2v0hOJwCPS4R3ZGqf3So9r2Ryx6KiGNTP50nb0VF9/aYzCFjy1j3Z7U004D4WS+RfIX27Bv1Xh5GnoiSin4aGDQG/SFy+Rr+pMfjfghPyw5c6bbHRZeKlcbGTCroSnpqvgyUZ5durqpW/yxOfZdbdBGGPNQx1TvlR3AkUwSMiJX4YVDn6uTMKUC0PDGaLDpi6kBTp/UgmQ2s5Dh07djWltidQa/juDyn2NHoUM1bW2yD811P+I2flwUHJzdDTGJDeV9pn9d8tPmA=
